Description: tutai92 - Project 02 - Deploy a high availability web app using CloudFormation - application specific resources

Parameters:
  ProjectName:
    Type: String
    Description: Project name used for tagging resources

Resources:
  WebAppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-web-servers-application
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectName}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeInstances
                  - ec2:AssociateAddress
                  - ec2:AllocateAddress
                  - ec2:DescribeAddresses
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:Get*
                  - s3:Put*
                Resource:
                  - !Sub "arn:aws:s3:::project02-udagram-s3bucket-tutai92"

  WebAppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref WebAppInstanceRole

Outputs: 
  WebAppInstanceProfile:
    Description: Instance Profile
    Value: !Ref WebAppInstanceProfile
    Export:
      Name: !Sub "${ProjectName}-instance-profile"