Description: tutai92 - Project 02 - Deploy a high availability web app using CloudFormation - networking resources

Parameters:
  ProjectName:
    Type: String
    Description: Project name used for tagging resources

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-IAM-Role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${ProjectName}-Policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeInstances
                  - ec2:AssociateAddress
                  - ec2:AllocateAddress
                  - ec2:DescribeAddresses
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:Get*
                  - s3:Put*
                Resource:
                  - !Sub "arn:aws:s3:::tutai92-s3-bucket"

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref IAMRole

Outputs:
  AppInstanceProfile:
    Description: App Instance Profile
    Value: !Ref AppInstanceProfile
    Export:
      Name: !Sub "${ProjectName}-App-Instance-Profile"