Description: tutai92 - Project 02 - Deploy a high availability web app using CloudFormation - networking resources

Parameters:
   ProjectName:
    Type: String
    Description: Project name used for tagging resources

Resources:
  ApplicationUdagramS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tutai92-s3-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# Outputs:
#   # Add your outputs here
#   S3BucketName:
#     Description: The name of the S3 bucket that will store the website content
#     Value: !Ref ApplicationUdagramS3Bucket
#     Export:
#       Name: !Sub "${EnvironmentName}-ApplicationUdagramS3Bucket"
  
#   S3BucketArn:
#     Description: The ARN of the S3 bucket that will store the website content
#     Value: !GetAtt ApplicationUdagramS3Bucket.Arn
#     Export:
#       Name: !Sub "${EnvironmentName}-UdagramS3BucketArn"